#!/bin/sh
# Air Sense Process
# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/root/MonashAirSense
DAEMON="python $DIR/MonashAirSense.py"
DAEMON_NAME=airsense

# This next line determines what user the script runs as.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

do_start () {
    echo starting
    start-stop-daemon -S -b -u $DAEMON_USER -n $DAEMON_NAME -p $PIDFILE -m -x $DAEMON
    echo started
}
do_stop () {
    echo stopping
    start-stop-daemon -K -p $PIDFILE
}
start_service (){
    do_start
}
case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
esac
start(){
    do_start
}
stop(){
    do_stop
}
exit 0
